### ISSUE TITLE
Web root variable to support relative paths for href attributes inside templates

### ISSUE THREAD

**Issue by dpilafian** [coderhaoxin/gulp-file-include#115]
Is there something like a `@@webRoot` variable that can be used inside a template to make a relative path?  More specifically, what's the recommended way to link to a CSS file from a template?

Example:

**index.html**

```html
@@include('templates/doc-begin.html')
<h1>Hello</h1>
<p>Welcome!</p>
@@include('templates/doc-end.html')
```

**support/index.html**

```html
@@include('templates/doc-begin.html')
<h1>Support</h1>
<p>RTFM</p>
@@include('templates/doc-end.html')
```

**templates/doc-begin.html**

```html
<!doctype html>
<html lang=en>
<head>
   <title>Website</title>
   <link rel=stylesheet href=@@webRoot/style.css>
</head>
<body>
```

The two `index.html` files are at different folder levels, so the relative path to the stylesheet in the `link` tag cannot be hardcoded.

**Comment by dpilafian** [comment]
Note: I currently have a workaround where I pass `webRoot` as `"."`, `".."`, or `"../.."` into each `@@include` call, but that's cumbersome and brittle.

**Comment by dpilafian** [comment]
Workaround is posted at:
http://stackoverflow.com/q/39418423

**Comment by richardtallent** [comment]
I have an ugly solution for you: run *two* gulp tasks run sequentially (using the `run-sequence` plugin).

The first would take a *master* template and *create* two new versions of your template: a "level 1" version and a "level 2" version, each with the appropriate paths.

The second gulp task would be your normal task, but rather than including the master template, your web pages would include the level-specific variant -- i.e., `index.html` and its siblings would `@@include('templates/doc-begin-l1.html')` and `support/index.html` and similar deeper pages would use `@@include('templates/doc-begin-l2.html')`.

**templates/doc-begin.html**
```
<!doctype html><html lang=en><head><title>Website</title>
   <link rel=stylesheet href=@@webRoot/style.css>
</head>
<body>
```

**templates/levels/doc-begin-l1.html**
`@@include('templates/doc-begin.html', {"webRoot","./"}`

**templates/levels/doc-begin-l2.html**
`@@include('templates/doc-begin.html', {"webRoot","../"}`

**gulpfile.js**
```
const runSequence = require("run-sequence");
gulp.task("makelevelspecifictemplates", function () {
	return gulp
		.src("./templates/levels/*.html")
		.pipe(fileInclude({ prefix: "@@", basepath: "./templates/"}))
		.pipe(gulp.dest("./templates/"));
});
gulp.task("html", function () {
	return gulp
		.src("./wwwroot/**/*.html")
		.pipe(fileInclude({ prefix: "@@", basepath: "./templates/"}))
		.pipe(gulp.dest("./output/"));
});
gulp.task("default", function (callback) {
	runSequence("makelevelspecifictemplates", "html", callback);
});
```

As long as the number of master templates and levels are finite, this would at least save a few keystrokes for each page.

**Comment by dpilafian** [comment]
It may be ugly, but it's creative!  I like it.  Thanks.

**Comment by coderhaoxin** [comment]
closed by https://github.com/coderhaoxin/gulp-file-include/pull/135

**Comment by coderhaoxin** [comment]
land 88706db790b2123958b4424468f689cecb95e78d
